## Configure this Discovery Server
#spring:
#  application:
#    name: mit-ms-discovery-server
#
## HTTP Server (Tomcat) Port
#server:
#  port: 6060
#
#eureka:
#  instance:
#    hostname: localhost
#    client: #Not a client
#    registerWithEureka: false
#    fetchRegistry: false
#  server:
#    waitTimeInMsWhenSyncEmpty: 0
#    
#    #renewalPercentThreshold: 0.49
    

    
server:
  port: 6060

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false